# Netlify build and deployment settings for your Wajibika Mazingira app.

# Build settings: Instructs Netlify how to build your Vite project.
[build]
  # This command builds the React app for production.
  command = "npm run build"
  
  # The folder where the built static files are located. Vite's default is 'dist'.
  publish = "dist"
  
  # The directory where your serverless functions live.
  functions = "netlify/functions"

# Function settings: Configures the bundling of your serverless functions.
[functions]
  # Use esbuild for faster and more modern function bundling, which is great for TypeScript.
  node_bundler = "esbuild"

# Redirects and Rewrites: This is the magic that makes your API calls work seamlessly.
# It proxies requests from your frontend to your serverless function.
[[redirects]]
  # Any request from your frontend to a path starting with /api/
  from = "/api/*"
  
  # ...will be transparently proxied to the corresponding Netlify function.
  # For example, a call to /api/gemini-proxy will be routed to your gemini-proxy.ts function.
  to = "/.netlify/functions/:splat"
  
  # A 200 status makes this a rewrite (proxy), not a redirect, so the URL doesn't change in the browser.
  status = 200

# Local development settings for when you run `ntl dev`
[dev]
  # Command to start the Vite development server.
  command = "npm run dev"

  # The port that Vite will run on (Vite's default).
  targetPort = 5173

  # The port that Netlify will serve the entire project from (including functions).
  port = 8888

  # This ensures `ntl dev` knows where to look for static assets.
  publish = "dist"
  
  # Automatically open the browser when you run `ntl dev`.
  autoLaunch = true
