# Netlify configuration for a single-page React application

[build]
  # This is a static site with no build command needed as all dependencies are from a CDN.
  command = "echo 'No build command required'"
  
  # The publish directory is the root of the project where index.html lives.
  publish = "."

# This rewrite rule is essential for single-page applications (SPAs).
# It ensures that any request that doesn't match a file is redirected to index.html,
# allowing the client-side JavaScript to handle routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
