# Netlify configuration for a single-page application

[build]
  # This is a static site with no build command needed.
  command = "echo 'No build command required'"
  
  # The publish directory is the root of the project.
  publish = "."

# This rewrite rule is essential for single-page applications (SPAs).
# It redirects all requests to index.html, allowing client-side routing to work.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
