import { Assessment } from '../types';
import { marked } from 'marked';

export const exportToPdf = (assessment: Assessment) => {
    const fileName = `${assessment.assessmentType}_Assessment_${assessment.projectName.replace(/\s+/g, '_')}.pdf`;
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
        alert('Could not open print window. Please disable your pop-up blocker.');
        return;
    }

    const reportHtml = marked.parse(assessment.report, { gfm: true, breaks: true });

    const assessorHtml = assessment.assessorName
      ? `<p><strong>Prepared By:</strong> ${assessment.assessorName}<em>, ${assessment.assessorType || 'Assessor'}</em></p>`
      : `<p><strong>Prepared By:</strong> _________________________________________</p>`;

    const printContent = `
        <html>
        <head>
            <title>${fileName}</title>
            <style>
                @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap');
                
                /* Paged media styles for printing */
                @page {
                    size: A4;
                    margin: 20mm; /* Standard A4 margins */
                    
                    @bottom-center {
                        content: "Report generated by Wajibika Mazingira";
                        font-family: 'Inter', sans-serif;
                        font-size: 0.8rem;
                        color: #94a3b8; /* slate-400 */
                        vertical-align: top; 
                        padding-top: 5mm; 
                    }
                }

                body {
                    font-family: 'Inter', sans-serif;
                    color: #334155; /* slate-700 */
                    line-height: 1.6;
                    margin: 0;
                    padding: 0;
                }

                /* Styles for the print preview window (non-print media) */
                .page {
                    background: white;
                    width: 210mm;
                    min-height: 297mm;
                    padding: 20mm;
                    margin: 10mm auto;
                    box-sizing: border-box;
                    box-shadow: 0 0 0.5cm rgba(0,0,0,0.5);
                }
                
                header {
                    border-bottom: 2px solid #16a34a; /* brand-green-600 */
                    padding-bottom: 1rem;
                    margin-bottom: 1.5rem;
                    page-break-inside: avoid;
                }
                header h1 {
                    font-size: 1.8rem;
                    color: #14532d; /* brand-green-900 */
                    margin: 0;
                }
                header p {
                    font-size: 1.1rem;
                    color: #166534; /* brand-green-800 */
                    margin: 0.25rem 0 0 0;
                }
                .metadata {
                    background-color: #f1f5f9; /* slate-100 */
                    border: 1px solid #e2e8f0; /* slate-200 */
                    border-radius: 8px;
                    padding: 1rem;
                    margin-bottom: 2rem;
                    page-break-inside: avoid;
                }
                .metadata p {
                    margin: 0.5rem 0;
                }
                .report-content h1, .report-content h2, .report-content h3 {
                    color: #14532d;
                    border-bottom: 1px solid #dcfce7; /* brand-green-100 */
                    padding-bottom: 0.5rem;
                    margin-top: 2rem;
                    page-break-after: avoid; /* Prevent a page break right after a heading */
                }
                .report-content p, .report-content li {
                    font-size: 1rem;
                }
                .report-content ul, .report-content ol {
                    padding-left: 1.5rem;
                }

                /* Styles specifically for when the document is being printed */
                @media print {
                    body {
                        /* Reset body margin for printing to let @page rule control it */
                        margin: 0;
                    }
                    .page {
                        /* Reset visual styles for the container when printing */
                        width: auto;
                        min-height: auto;
                        margin: 0;
                        padding: 0;
                        box-shadow: none;
                        background: none;
                    }
                }
            </style>
        </head>
        <body>
            <div class="page">
                <header>
                    <h1>${assessment.assessmentType} Impact Assessment</h1>
                    <p>${assessment.projectName}</p>
                </header>

                <div class="metadata">
                    <p><strong>Project Name:</strong> ${assessment.projectName}</p>
                    <p><strong>Project Proponent:</strong> ${assessment.projectProponent}</p>
                    <p><strong>Location:</strong> ${assessment.location}</p>
                    <p><strong>Project Type:</strong> ${assessment.projectType}</p>
                    <p><strong>Assessment Date:</strong> ${new Date(assessment.createdAt).toLocaleDateString()}</p>
                    ${assessorHtml}
                </div>

                <div class="report-content">
                    ${reportHtml}
                </div>
            </div>
        </body>
        </html>
    `;
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.focus();
    // Use a timeout to ensure all assets are loaded before printing
    setTimeout(() => {
        printWindow.print();
        printWindow.close();
    }, 500);
};