import React, { useEffect, useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { Assessment, ManualFormData, AssessmentType, EIAFormData, CIAFormData, SIAFormData, HIAFormData } from '../types';
import { useAssessments } from '../contexts/AssessmentContext';
import { useLayout } from '../contexts/LayoutContext';
import { Button } from '../components/common/Button';
import { ArrowDownTrayIcon } from '../components/icons/ArrowDownTrayIcon';

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div className="bg-white p-6 rounded-lg shadow-sm mb-6">
    <h3 className="text-xl font-bold text-gray-800 border-b pb-2 mb-4 border-gray-200">{title}</h3>
    {children}
  </div>
);

const getSeverityColor = (severity: string) => {
    switch (severity?.toLowerCase()) {
        case 'high': return 'bg-red-100 text-red-800';
        case 'medium': return 'bg-yellow-100 text-yellow-800';
        case 'low': return 'bg-green-100 text-green-800';
        default: return 'bg-gray-100 text-gray-800';
    }
}

const formatReportForDownload = (assessment: Assessment): string => {
    const { report, project_name, location, date } = assessment;
    let content = `ENVIRONMENTAL ASSESSMENT REPORT\n`;
    content += `===================================\n\n`;
    content += `Project Name: ${project_name}\n`;
    content += `Location: ${location}\n`;
    content += `Assessment Date: ${new Date(date).toLocaleDateString()}\n`;
    content += `Report Title: ${report.assessmentTitle}\n\n`;
    content += `-----------------------------------\n\n`;

    content += `1. PROJECT SUMMARY\n\n`;
    content += `${report.projectSummary}\n\n`;

    content += `2. APPLICABLE LEGAL FRAMEWORK (KENYA)\n\n`;
    report.legalFramework?.forEach(item => {
        content += `  - Statute: ${item.statute}\n`;
        content += `    Relevance: ${item.relevance}\n\n`;
    });

    content += `3. POTENTIAL IMPACTS\n\n`;
    report.potentialImpacts?.forEach(impact => {
        content += `  - Impact Area: ${impact.impactArea}\n`;
        content += `    Severity: ${impact.severity}\n`;
        content += `    Description: ${impact.description}\n\n`;
    });

    content += `4. PROPOSED MITIGATION MEASURES\n\n`;
    report.mitigationMeasures?.map((item) => {
        content += `  - Measure: ${item.measure}\n`;
        content += `    Implementation: ${item.implementation}\n\n`;
    });

    content += `5. STAKEHOLDER ENGAGEMENT PLAN\n\n`;
    content += `${report.stakeholderEngagementPlan}\n\n`;

    content += `6. RECOMMENDATIONS\n\n`;
    content += `${report.recommendations}\n\n`;

    content += `===================================\n`;
    content += `Report generated by Wajibika Mazingira on ${new Date().toLocaleString()}.\n`;

    return content;
};

const ManualFormDataDisplay: React.FC<{ data: ManualFormData }> = ({ data }) => {
    const renderField = (label: string, value: string) => (
        <div key={label} className="py-4 sm:grid sm:grid-cols-3 sm:gap-4 border-b last:border-b-0 border-gray-100">
            <dt className="text-sm font-semibold text-gray-600">{label}</dt>
            <dd className="mt-1 text-sm text-gray-800 sm:mt-0 sm:col-span-2 whitespace-pre-wrap">{value || <span className="italic text-gray-400">Not provided</span>}</dd>
        </div>
    );

    let fields: {label: string, value: string}[] = [];
    const { assessmentType } = data;

    if (assessmentType === AssessmentType.EIA) {
        const eiaData = data as EIAFormData;
        fields = [
            { label: 'Environmental Setting', value: eiaData.environmentalSetting },
            { label: 'Potential Environmental Impacts', value: eiaData.potentialImpacts },
            { label: 'Proposed Mitigation Measures', value: eiaData.mitigationMeasures },
            { label: 'Public Consultation Summary', value: eiaData.publicConsultationSummary },
        ];
    } else if (assessmentType === AssessmentType.CIA) {
        const ciaData = data as CIAFormData;
        fields = [
            { label: 'GHG Emissions Estimate', value: ciaData.ghgEmissionsEstimate },
            { label: 'Vulnerability to Climate Change', value: ciaData.climateVulnerability },
            { label: 'Proposed Adaptation Measures', value: ciaData.adaptationMeasures },
            { label: 'Alignment with NCCAP', value: ciaData.nccapAlignment },
        ];
    } else if (assessmentType === AssessmentType.SIA) {
        const siaData = data as SIAFormData;
        fields = [
            { label: 'Affected Communities/Demographics', value: siaData.affectedCommunities },
            { label: 'Potential Social Impacts', value: siaData.potentialSocialImpacts },
            { label: 'Community Engagement Plan', value: siaData.communityEngagementPlan },
            { label: 'Benefit Sharing Mechanism', value: siaData.benefitSharingMechanism },
        ];
    } else if (assessmentType === AssessmentType.HIA) {
        const hiaData = data as HIAFormData;
        fields = [
            { label: 'Potential Health Risks', value: hiaData.potentialHealthRisks },
            { label: 'Affected Population Groups', value: hiaData.affectedPopulationGroups },
            { label: 'Health System Capacity Analysis', value: hiaData.healthSystemCapacity },
            { label: 'Proposed Health Mitigation Measures', value: hiaData.healthMitigationMeasures },
        ];
    }

    return (
        <dl>
            {fields.map(field => renderField(field.label, field.value))}
        </dl>
    )
}


export const AssessmentDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const { getAssessmentById, isLoading } = useAssessments();
  const { setTitle } = useLayout();
  const [assessment, setAssessment] = useState<Assessment | null | undefined>(undefined);

  useEffect(() => {
    if (!isLoading && id) {
      const currentAssessment = getAssessmentById(id);
      setAssessment(currentAssessment);
      if (currentAssessment) {
        setTitle(currentAssessment.project_name);
      } else {
        setTitle('Assessment Not Found');
      }
    }
  }, [id, getAssessmentById, isLoading, setTitle]);
  
  const handleDownload = () => {
    if (!assessment || assessment.type !== 'AI') return;
    const reportText = formatReportForDownload(assessment);
    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    const fileName = `${assessment.project_name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_assessment.txt`;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (isLoading || assessment === undefined) {
    return (
      <div className="text-center py-12">
        <h4 className="text-lg font-medium text-gray-700">Loading assessment details...</h4>
      </div>
    );
  }

  if (!assessment) {
    return <Navigate to="/dashboard" />;
  }

  const { type, report, project_name, location, date, manual_form } = assessment;

  if (type === 'Manual') {
    return (
        <div>
            <div className="mb-8">
                <h2 className="text-3xl font-bold text-gray-900">{report.assessmentTitle}</h2>
                <div className="mt-2 flex flex-col sm:flex-row sm:items-center sm:space-x-4 text-sm text-gray-500">
                    <span>Project: <span className="font-medium text-gray-700">{project_name}</span></span>
                    <span className="hidden sm:inline">|</span>
                    <span>Location: <span className="font-medium text-gray-700">{location}</span></span>
                    <span className="hidden sm:inline">|</span>
                    <span>Date Submitted: <span className="font-medium text-gray-700">{new Date(date).toLocaleDateString()}</span></span>
                </div>
            </div>

            <Section title="Assessment Summary">
                <p className="text-gray-600 leading-relaxed italic">{report.projectSummary}</p>
            </Section>

            <Section title="Manual Assessment Form Details">
                {manual_form ? <ManualFormDataDisplay data={manual_form} /> : <p className="text-gray-500">No detailed form data was submitted for this manual record.</p>}
            </Section>
            
            <div className="text-center mt-8">
                <Link to="/dashboard" className="text-brand-green-light hover:text-brand-green font-semibold">
                    &larr; Back to Dashboard
                </Link>
            </div>
        </div>
    );
  }

  return (
    <div>
        <div className="flex justify-between items-start mb-8">
            <div>
                <h2 className="text-3xl font-bold text-gray-900">{report.assessmentTitle}</h2>
                <div className="mt-2 flex items-center space-x-4 text-sm text-gray-500">
                    <span>Project: <span className="font-medium text-gray-700">{project_name}</span></span>
                    <span>Location: <span className="font-medium text-gray-700">{location}</span></span>
                    <span>Date: <span className="font-medium text-gray-700">{new Date(date).toLocaleDateString()}</span></span>
                </div>
            </div>
             <Button onClick={handleDownload} variant="secondary">
                <ArrowDownTrayIcon className="h-5 w-5 mr-2" />
                Download Report
            </Button>
        </div>

        <Section title="Project Summary">
            <p className="text-gray-600 leading-relaxed">{report.projectSummary}</p>
        </Section>
        
        <Section title="Applicable Legal Framework (Kenya)">
            <ul className="space-y-4">
                {report.legalFramework?.map((item, index) => (
                    <li key={index} className="p-4 bg-gray-50 rounded-md border border-gray-200">
                        <p className="font-semibold text-gray-800">{item.statute}</p>
                        <p className="text-gray-600 mt-1">{item.relevance}</p>
                    </li>
                ))}
            </ul>
        </Section>
        
        <Section title="Potential Impacts">
            <div className="space-y-4">
                {report.potentialImpacts?.map((impact, index) => (
                    <div key={index} className="p-4 border rounded-lg">
                        <div className="flex justify-between items-start">
                           <h4 className="font-semibold text-gray-800">{impact.impactArea}</h4>
                           <span className={`px-2 py-1 text-xs font-semibold rounded-full ${getSeverityColor(impact.severity)}`}>
                               {impact.severity}
                           </span>
                        </div>
                        <p className="text-gray-600 mt-2">{impact.description}</p>
                    </div>
                ))}
            </div>
        </Section>
        
        <Section title="Proposed Mitigation Measures">
            <ul className="list-disc list-inside space-y-3 text-gray-600">
                {report.mitigationMeasures?.map((item, index) => (
                    <li key={index}>
                        <span className="font-semibold text-gray-700">{item.measure}:</span> {item.implementation}
                    </li>
                ))}
            </ul>
        </Section>

        <Section title="Stakeholder Engagement Plan">
            <p className="text-gray-600 leading-relaxed">{report.stakeholderEngagementPlan}</p>
        </Section>

        <Section title="Recommendations">
            <p className="text-gray-600 leading-relaxed font-medium">{report.recommendations}</p>
        </Section>

        <div className="text-center mt-8">
            <Link to="/dashboard" className="text-brand-green-light hover:text-brand-green font-semibold">
                &larr; Back to Dashboard
            </Link>
        </div>
    </div>
  );
};